import type {EducationSummaryProps} from "../../components/summary/EducationSummary.tsx";
import type {TechnologyProps} from "../../components/summary/Technology.tsx";
import {ai, backend, database, devops, frontend, ide, language, os, sdk} from "./Technologies.ts";

export const education: EducationSummaryProps[] = [
  {
    title: "Baccalauréat général scientifique",
    imgsrc: "https://media.licdn.com/dms/image/v2/C4D0BAQGLcVtChMc3wA/company-logo_200_200/company-logo_200_200/0/1631364762862?e=1755734400&v=beta&t=h0fBiHaS7ax7pCED_eCUGYikJaKvApSGkzb6Uwrrfrk",
    school: "Lycée Martin Luther King",
    city: "Bussy-Saint-Georges",
    description: "",
    technologies: [
      language.get("Python"),
      language.get("HTML"),
      os.get("Windows"),
    ] as TechnologyProps[],
    results: "14.20 / 20 de moyenne générale, mention Bien",
    obtentionDate: new Date(2019, 7, 22),
  },
  {
    title: "Licence Informatique",
    imgsrc: "https://sciences.edu.umontpellier.fr/files/2022/06/Faculte-des-Sciences-2022-RVB-scaled.jpg",
    school: "Faculté des Sciences",
    city: "Montpellier",
    description: "La Licence informatique offre une formation générale en informatique équilibrée, tant sur les aspects théoriques et fondamentaux que sur les aspects appliqués et pratiques de l'informatique. Elle s'adresse aux étudiants souhaitant s'orienter vers des études longues en informatique en Master ou vers des études plus courtes en licence professionnelle.",
    technologies: [
      language.get("C"),
      language.get("C++"),
      language.get("Java"),
      language.get("HTML"),
      language.get("CSS"),
      language.get("PHP"),
      language.get("JavaScript"),
      language.get("Python"),
      language.get("Go"),
      language.get("Rocq"),
      language.get("LaTeX"),
      database.get("MySQL"),
      devops.get("Git"),
      devops.get("SonarQube Server"),
      os.get("Linux"),
    ] as TechnologyProps[],
    results: "12 / 20 de moyenne générale, mention Assez Bien",
    obtentionDate: new Date(2022, 11, 9),
    link: "https://informatique-fds.edu.umontpellier.fr/etudiants/offre-de-formation-licence/"
  },
  {
    title: "Cursus Master en Ingénierie Informatique",
    imgsrc: "https://reseau-figure.fr/_nuxt/logo-reseau-figure.HLtO9i_p.svg",
    school: "Faculté des Sciences",
    city: "Montpellier",
    description: "Le Cursus Master en Ingénierie (CMI) Informatique s’appuie sur les enseignements de la Licence Informatique commune aux quatre parcours puis sur le Master Informatique. Le CMI propose sur les 5 ans une formation exigeante et renforcée en langue (passage du TOEIC), modules d'OSEC (management, innovation, communication), projets dès la L1 et stages obligatoires (52 semaines cumulées sur 5 ans). Les activités de mise en situation (stages et projets) sont encadrées par les laboratoires porteurs du CMI ou les entreprises partenaires.",
    technologies: [
      language.get("C++"),
      language.get("LaTeX"),
      devops.get("Git"),
      ide.get("Qt"),
    ] as TechnologyProps[],
    results: "Formation inachevée à la fin du M1",
    link: "https://informatique-fds.edu.umontpellier.fr/etudiants/cmi-informatique-cursus-master-en-ingenierie/"
  },
  {
    title: "Master Informatique Génie Logiciel",
    imgsrc: "https://sciences.edu.umontpellier.fr/files/2022/06/Faculte-des-Sciences-2022-RVB-scaled.jpg",
    school: "Faculté des Sciences",
    city: "Montpellier",
    description: "Le Master Informatique Génie Logiciel propose une formation centrée autour de l’automatisation des étapes du cycle de vie du logiciel, tout en assurant la qualité du produit logiciel. Toutes les étapes du cycle de vie du logiciel sont concernées : de la conception à la maintenance en passant par le développement, le test et la gestion de versions. La présence de nombreux intervenants industriels garantit l’adéquation de la formation avec les exigences du milieu industriel.",
    technologies: [
      language.get("C"),
      language.get("C++"),
      language.get("Java"),
      language.get("HTML"),
      language.get("CSS"),
      language.get("PHP"),
      language.get("JavaScript"),
      language.get("Python"),
      language.get("Rocq"),
      language.get("LaTeX"),
      language.get("Dart"),
      database.get("MySQL"),
      database.get("MongoDB"),
      backend.get("Spring Boot"),
      backend.get("Node.js"),
      backend.get("Symfony"),
      backend.get("Express.js"),
      frontend.get("Angular"),
      devops.get("Git"),
      devops.get("Docker"),
      ai.get("TensorFlow"),
      ai.get("NLTK"),
      ai.get("scikit-learn"),
      ai.get("gensim"),
      ide.get("Android Studio"),
      ide.get("Arduino IDE"),
      os.get("Linux"),
      os.get("Windows"),
      sdk.get("Flutter"),
    ] as TechnologyProps[],
    results: "13 / 20 de moyenne générale, mention Assez Bien",
    obtentionDate: new Date(2024, 11, 6),
    link: "https://informatique-fds.edu.umontpellier.fr/etudiants/master-informatique-parcours/parcours-gl-genie-logiciel/",
  }
]