import type {EducationSummaryProps} from "../components/summary/EducationSummary.tsx";
import type {TechnologyProps} from "../components/summary/Technology.tsx";
import {ai, backend, database, devops, frontend, ide, language, os, sdk} from "./project/Technologies.ts";

//TODO: ajouter descriptions / imgsrcs formations
export const education: EducationSummaryProps[] = [
  {
    title: "Baccalauréat général scientifique",
    school: "Lycée Martin Luther King",
    city: "Bussy-Saint-Georges",
    description: "",
    technologies: [
      language.get("Python"),
      language.get("HTML"),
      os.get("Windows"),
    ] as TechnologyProps[],
    results: "14.20 / 20 de moyenne, mention Bien",
    obtentionDate: new Date(2019, 7, 22),
  },
  {
    title: "Licence Informatique",
    school: "Faculté des Sciences",
    city: "Montpellier",
    description: "",
    technologies: [
      language.get("C"),
      language.get("C++"),
      language.get("Java"),
      language.get("HTML"),
      language.get("CSS"),
      language.get("PHP"),
      language.get("JavaScript"),
      language.get("Python"),
      language.get("Go"),
      language.get("Rocq"),
      language.get("LaTeX"),
      database.get("MySQL"),
      devops.get("Git"),
      devops.get("SonarQube Server"),
      os.get("Linux"),
    ] as TechnologyProps[],
    results: "12 / 20 de moyenne, mention Assez Bien",
    obtentionDate: new Date(2022, 11, 9),
  },
  {
    title: "Cursus Master en Ingénierie",
    school: "Faculté des Sciences",
    city: "Montpellier",
    description: "",
    technologies: [
      language.get("C++"),
      language.get("LaTeX"),
      devops.get("Git"),
      ide.get("Qt"),
    ] as TechnologyProps[],
    results: "Formation inachevée à la fin du M1",
  },
  {
    title: "Master Informatique Génie Logiciel",
    school: "Faculté des Sciences",
    city: "Montpellier",
    description: "",
    technologies: [
      language.get("C"),
      language.get("C++"),
      language.get("Java"),
      language.get("HTML"),
      language.get("CSS"),
      language.get("PHP"),
      language.get("JavaScript"),
      language.get("Python"),
      language.get("Rocq"),
      language.get("LaTeX"),
      language.get("Dart"),
      database.get("MySQL"),
      database.get("MongoDB"),
      backend.get("Spring Boot"),
      backend.get("Node.js"),
      backend.get("Symfony"),
      backend.get("Express.js"),
      frontend.get("Angular"),
      devops.get("Git"),
      devops.get("Docker"),
      ai.get("TensorFlow"),
      ai.get("NLTK"),
      ai.get("scikit-learn"),
      ai.get("gensim"),
      ide.get("Android Studio"),
      ide.get("Arduino IDE"),
      os.get("Linux"),
      os.get("Windows"),
      sdk.get("Flutter"),
    ] as TechnologyProps[],
    results: "13 / 20 de moyenne, mention Assez Bien",
    obtentionDate: new Date(2024, 11, 6),
  }
]